spring:
  datasource:
    url: jdbc:mysql://localhost:3306/locationvoituredb?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
  #specify DBMS
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true


server:
  port: 8801

#error:
  #message = Required or invalid fields!
#logging.level.com.voiture=DEBUG


    